services:
  - type: web
    name: text-to-image-service
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: PORT
        value: "7860"
      - key: HF_MODEL_ID
        value: ""
      - key: HF_HUB_TOKEN
        fromSecret: HF_HUB_TOKEN
    healthCheckPath: "/"
